services:
  web:
    platform: linux/amd64
    build:
      context: .
    command: sh -c "npm install && exec wasp start"
    depends_on:
      db:
        condition: service_healthy
    environment:
      REACT_APP_API_URL: http://${APP_HOST}:${WEB_SERVER_PORT}
      WASP_WEB_CLIENT_URL: http://${APP_HOST}:${WEB_CLIENT_PORT}
      WASP_SERVER_URL: http://${APP_HOST}:${WEB_SERVER_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: ${WEB_SERVER_PORT}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
      - "5555:5555" # Prisma Studio
    volumes:
      - .:/app
      - wasp-cache:/root/.cache/wasp
      - wasp-generated:/app/.wasp
      - wasp-node-modules:/app/node_modules
    stdin_open: true
    tty: true

  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  wasp-cache:
  wasp-generated:
  wasp-node-modules:
  postgres-data:
